/**
 * @spec    001-initial-dev
 * @phase   3 — Athletes, cross-sport ratings, roster
 * @task    T-3.14 — Starter roster: generated fictional athletes, enough for both sports
 * @story   US-5.6 — Start with something to play with
 * @design  05-data-model.md §2 (athlete), §4 (rarity)
 * @invariant INV-2 (seeded PRNG only — same seed = same roster on any device)
 *
 * Purpose: generates a deterministic roster of fictional athletes ready to play, enough for two
 * basketball teams and two soccer teams plus spares. Names are invented from linguistic pools to
 * avoid collision with real athletes. Heights are coherent with role (guards shorter than
 * centres). Rarity is believable (mostly common/uncommon with a few rare and at most one or two
 * epic). Every athlete carries `source: 'starter'` and determinism is assured through the seeded
 * RNG, so the same seed produces byte-identical rosters across devices.
 *
 * The roster is generated once at a seed (defaulting to `'starter'`), producing a fixed number of
 * athletes. This is what makes a fresh install consistent and repeatable.
 */
import { createRng, type Rng } from '../engine/rng.ts';
import type { SportId } from '../sports/types.ts';
import { rollAthlete } from './create.ts';
import type { Athlete, Rarity } from './types.ts';

/**
 * Total athletes generated by `generateStarterRoster`. Enough for:
 * - 2 basketball teams: 5 × 2 = 10
 * - 2 soccer teams: 11 × 2 = 22
 * - Spares: 6
 * Total: 38
 */
export const STARTER_ROSTER_SIZE = 38;

/** Role archetypes with height ranges for basketball. Mapped by role index. */
interface HeightArchetype {
  readonly heightRange: { readonly min: number; readonly max: number };
  readonly description: string;
}

const BASKETBALL_ARCHETYPES: Readonly<Record<number, HeightArchetype>> = {
  // PG (Point Guard) — index 0
  0: { heightRange: { min: 180, max: 190 }, description: 'Point Guard' },
  // SG (Shooting Guard) — index 1
  1: { heightRange: { min: 185, max: 195 }, description: 'Shooting Guard' },
  // SF (Small Forward) — index 2
  2: { heightRange: { min: 195, max: 205 }, description: 'Small Forward' },
  // PF (Power Forward) — index 3
  3: { heightRange: { min: 200, max: 210 }, description: 'Power Forward' },
  // C (Centre) — index 4
  4: { heightRange: { min: 205, max: 215 }, description: 'Centre' },
};

/** Role archetypes with height ranges for soccer. Mapped by position index. */
const SOCCER_ARCHETYPES: Readonly<Record<number, HeightArchetype>> = {
  // GK (Goalkeeper) — 0
  0: { heightRange: { min: 185, max: 195 }, description: 'Goalkeeper' },
  // Defenders — 1-4
  1: { heightRange: { min: 180, max: 192 }, description: 'Defender' },
  2: { heightRange: { min: 180, max: 192 }, description: 'Defender' },
  3: { heightRange: { min: 180, max: 192 }, description: 'Defender' },
  4: { heightRange: { min: 180, max: 192 }, description: 'Defender' },
  // Midfielders — 5-8
  5: { heightRange: { min: 175, max: 188 }, description: 'Midfielder' },
  6: { heightRange: { min: 175, max: 188 }, description: 'Midfielder' },
  7: { heightRange: { min: 175, max: 188 }, description: 'Midfielder' },
  8: { heightRange: { min: 175, max: 188 }, description: 'Midfielder' },
  // Forwards — 9-10
  9: { heightRange: { min: 175, max: 190 }, description: 'Forward' },
  10: { heightRange: { min: 175, max: 190 }, description: 'Forward' },
};

/** First names from diverse linguistic origins. */
const FIRST_NAMES = [
  'Marcus',
  'David',
  'James',
  'Robert',
  'Michael',
  'Daniel',
  'Christopher',
  'Anthony',
  'Kevin',
  'Paul',
  'Steven',
  'Brandon',
  'Eric',
  'Jason',
  'Jose',
  'Carlos',
  'Juan',
  'Luis',
  'Miguel',
  'Diego',
  'Alejandro',
  'Cristian',
  'Luca',
  'Marco',
  'Alessandro',
  'Giuseppe',
  'Andrea',
  'Matteo',
  'Andres',
  'Jorge',
  'Francisco',
  'Ricardo',
  'Manuel',
  'Angel',
  'Fernando',
  'Pedro',
  'Sergio',
  'Miguel',
  'Oscar',
  'Eduardo',
  'Javier',
  'Adrian',
  'Santiago',
  'Sebastian',
  'Felipe',
  'Guillermo',
  'Rafael',
  'Leonardo',
  'Ahmed',
  'Mohammed',
  'Hassan',
  'Ali',
  'Ibrahim',
  'Mustafa',
  'Omar',
  'Karim',
  'Nasser',
  'Samir',
  'Hamid',
  'Rashid',
  'Walid',
  'Tariq',
  'Khalid',
  'Amjad',
  'Jamal',
  'Malik',
  'Amir',
  'Tahir',
  'Adil',
  'Faisal',
  'Laurent',
  'Philippe',
  'Jean',
  'Pierre',
  'Jacques',
  'Michel',
  'Henri',
  'Francois',
  'Thierry',
  'Andre',
  'Vincent',
  'Bernard',
  'Claude',
  'Georges',
  'Etienne',
  'Alain',
  'Christian',
  'Daniel',
  'Rudi',
  'Klaus',
  'Jurgen',
  'Wolfgang',
  'Hans',
  'Karl',
  'Dieter',
  'Werner',
  'Ernst',
  'Gunter',
  'Helmut',
  'Horst',
  'Johan',
  'Pieter',
  'Willem',
  'Kees',
  'Sven',
  'Lars',
  'Ole',
  'Per',
  'Erik',
  'Anders',
  'Torsten',
  'Bjorn',
  'Magnus',
  'Stefan',
  'Jens',
  'Henrik',
  'Mikael',
  'Christer',
  'Pavel',
  'Igor',
  'Dmitri',
  'Sergei',
  'Yuri',
  'Boris',
  'Vladimir',
  'Gennady',
  'Anatoly',
  'Victor',
  'Nikolai',
  'Alexei',
  'Vlad',
  'Oleg',
  'Andrey',
  'Nikolay',
  'Vasily',
  'Nadia',
  'Olga',
  'Elena',
  'Tatiana',
  'Anna',
  'Svetlana',
  'Marina',
  'Irina',
  'Vera',
  'Larisa',
  'Natasha',
  'Yuki',
  'Takeshi',
  'Kenji',
  'Hiroshi',
  'Masao',
  'Toshiro',
  'Haruo',
  'Fumio',
  'Akira',
  'Toru',
  'Saburo',
  'Daichi',
  'Keisuke',
  'Naoto',
  'Satoru',
  'Jiro',
  'Park',
  'Kim',
  'Lee',
  'Choi',
  'Jung',
  'Han',
  'Sung',
  'Min',
  'Hyun',
  'Chang',
  'Young',
  'Jin',
  'Hoang',
  'Nguyen',
  'Tran',
  'Pham',
  'Dang',
  'Vu',
  'Cao',
  'Ngo',
  'Duong',
  'Phan',
  'Bui',
  'Le',
  'Ly',
] as const;

/** Surnames from diverse linguistic origins. */
const SURNAMES = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Rodriguez',
  'Martinez',
  'Lee',
  'White',
  'Harris',
  'Martin',
  'Davis',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Perez',
  'Sanchez',
  'Morris',
  'Rogers',
  'Morgan',
  'Peterson',
  'Cooper',
  'Reed',
  'Bell',
  'Chapman',
  'Kennedy',
  'Byrd',
  'Fox',
  'Rivers',
  'Cole',
  'Day',
  'Garrett',
  'Hale',
  'Hardy',
  'Harvey',
  'Hawkins',
  'Holland',
  'Hopkins',
  'Horn',
  'Houston',
  'Huff',
  'Hughes',
  'Hunt',
  'Hunter',
  'Hurley',
  'Hutchins',
  'Hutchison',
  'Hynes',
  'Iacono',
  'Iannaccone',
  'Rossi',
  'Russo',
  'Bianchi',
  'Ferrari',
  'Esposito',
  'Gallo',
  'Rizzo',
  'Conti',
  'Marino',
  'Lombardi',
  'Moretti',
  'Ferraro',
  'Cortese',
  'Benedetti',
  'Barbieri',
  'Cappelli',
  'Mueller',
  'Schmidt',
  'Schneider',
  'Schwartz',
  'Schwarz',
  'Schweitzer',
  'Seaver',
  'Segal',
  'Seltzer',
  'Semple',
  'Shafer',
  'Shaffer',
  'Sharpe',
  'Shaw',
  'Shea',
  'Shelly',
  'Shelton',
  'Shepherd',
  'Sheppard',
  'Sheridan',
  'Sherman',
  'Shields',
  'Shilts',
  'Shine',
  'Shoemaker',
  'Shorey',
  'Short',
  'Shoup',
  'Shove',
  'Shown',
  'Shrum',
  'Shue',
  'Vargas',
  'Velasquez',
  'Velasquez',
  'Velazquez',
  'Veliz',
  'Vella',
  'Vellarreal',
  'Velleman',
  'Velverton',
  'Venables',
  'Venant',
  'Vencill',
  'Vender',
  'Vendley',
  'Venegas',
  'Venezia',
  'Veneziano',
  'Venglar',
  'Venhuizen',
  'Venkatesh',
  'Venn',
  'Venneman',
  'Vensel',
  'Venser',
  'Nolan',
  'Noll',
  'Nolle',
  'Nolley',
  'Nollman',
  'Nomeland',
  'Nomland',
  'Noneman',
  'Nones',
  'Nong',
  'Nonimann',
  'Nonini',
  'Nonn',
  'Nonne',
  'Nonnenberg',
  'Nonnenmann',
  'Nonnenmacher',
  'Nora',
  'Norbert',
  'Norby',
  'Nord',
  'Nordahl',
  'Nordberg',
  'Nordbert',
  'Nordeen',
  'Norden',
  'Nordenhall',
  'Nordenholz',
  'Nordenson',
  'Norderhaug',
  'Nordgren',
  'Nordic',
  'Tani',
  'Tanigaki',
  'Tanikawa',
  'Tanino',
  'Tanita',
  'Tanitsu',
  'Tank',
  'Tanka',
  'Tankard',
  'Tanke',
  'Tankersly',
  'Tankersley',
  'Tanksley',
  'Tankus',
  'Tanley',
  'Tanna',
  'Tannabe',
  'Tannady',
  'Tannager',
  'Tannahel',
  'Tannahill',
  'Tannahill',
  'Tannajhill',
  'Tannaka',
  'Hyun',
  'Hynes',
  'Hyson',
  'Hysell',
  'Hysmith',
  'Hyson',
  'Hyte',
  'Hyton',
  'Haynes',
  'Hayworth',
  'Hazard',
  'Hazley',
  'Hazlewood',
  'Hazlett',
  'Hazlip',
  'Hazen',
  'Hazer',
  'Hazlip',
  'Hazig',
  'Hazim',
  'Hazinger',
  'Hazins',
  'Hazirt',
  'Hazlip',
  'Okafor',
  'Okamura',
  'Okasaki',
  'Okatsha',
  'Okawara',
  'Okaze',
  'Okeh',
  'Okehie',
  'Okelley',
  'Okelly',
  'Okene',
  'Oker',
  'Okerman',
  'Okermeier',
  'Okero',
  'Okerson',
  'Okerstrom',
  'Okes',
  'Okeson',
  'Okesson',
  'Okey',
  'Okezzie',
  'Okham',
  'Okimoto',
  'Zhang',
  'Liu',
  'Li',
  'Wang',
  'Chen',
  'Yang',
  'Huang',
  'Zhao',
  'Wu',
  'Zhou',
  'Xu',
  'Sun',
  'Ma',
  'Zhu',
  'Lin',
  'He',
  'Guo',
  'He',
  'Gao',
  'Zheng',
  'Luo',
  'Liang',
  'Song',
  'Tang',
  'Patel',
  'Singh',
  'Sharma',
  'Kumar',
  'Verma',
  'Iyer',
  'Nair',
  'Gupta',
  'Menon',
  'Desai',
  'Joshi',
  'Agarwal',
  'Chopra',
  'Bhat',
  'Pillai',
  'Rao',
  'Sinha',
  'Mishra',
  'Pandey',
  'Srivastava',
  'Dwivedi',
  'Tripathi',
  'Banerjee',
  'Chatterjee',
] as const;

/**
 * Picks a name from a pool deterministically based on the RNG state. The seeded choice ensures
 * the same RNG position produces the same name on every device.
 */
function pickName<T extends readonly string[]>(rng: Rng, pool: T): T[number] {
  const index = rng.int(0, pool.length);
  return pool[index] as T[number];
}

/**
 * Ensures all names in the roster are unique by tracking used names and regenerating collisions.
 * The seeded RNG ensures this process is deterministic — a collision regenerates to the same
 * alternate name on every device.
 */
function generateUniqueName(rng: Rng, usedNames: Set<string>, maxAttempts = 100): string {
  for (let i = 0; i < maxAttempts; i++) {
    const first = pickName(rng, FIRST_NAMES);
    const last = pickName(rng, SURNAMES);
    const name = `${first} ${last}`;

    if (!usedNames.has(name)) {
      usedNames.add(name);
      return name;
    }
  }

  // Fallback: use the counters to guarantee uniqueness if pool is exhausted
  const name = `Player ${usedNames.size + 1}`;
  usedNames.add(name);
  return name;
}

/**
 * Generates height deterministically based on role and RNG. Centres are taller on average than
 * point guards, and so on. The height range is used to make role-based athletes coherent.
 */
function rollHeight(rng: Rng, archetype: HeightArchetype): number {
  const { min, max } = archetype.heightRange;
  return Math.round(rng.float(min, max + 0.99));
}

/**
 * Generates a rarity deterministically with a believable distribution:
 * - ~60% common
 * - ~25% uncommon
 * - ~12% rare
 * - ~2% epic
 * - 0% legendary (fresh install should not start with franchise athletes)
 *
 * The seeded RNG ensures this distribution is deterministic.
 */
function rollRarity(rng: Rng, position: number, totalAthletes: number): Rarity {
  const roll = rng.next();

  // Ensure at most one epic athlete in the entire roster by position
  if (roll < 0.02 && position < Math.floor(totalAthletes * 0.026)) return 'epic';
  if (roll < 0.14) return 'rare';
  if (roll < 0.39) return 'uncommon';
  return 'common';
}

/**
 * Generates the starter roster deterministically. The same seed always produces a byte-identical
 * roster on every device. This is the initial athlete pool a fresh install receives.
 *
 * @param seed — the RNG seed (defaults to 'starter' for a consistent default roster)
 * @returns an array of STARTER_ROSTER_SIZE athletes, ready to use
 */
export function generateStarterRoster(seed = 'starter'): Athlete[] {
  const rng = createRng(seed);
  const athletes: Athlete[] = [];
  const usedNames = new Set<string>();
  // A fixed base time for all starter athletes, ensuring determinism and consistency.
  // Use a reasonable timestamp: 2024-01-01T00:00:00Z = 1704067200000
  const baseCreatedAt = 1_704_067_200_000;

  // Basketball: 2 teams × 5 players = 10 athletes
  for (let team = 0; team < 2; team++) {
    for (let roleIndex = 0; roleIndex < 5; roleIndex++) {
      const archetype = BASKETBALL_ARCHETYPES[roleIndex]!;
      const name = generateUniqueName(rng, usedNames);
      const heightCm = rollHeight(rng, archetype);
      const rarity = rollRarity(rng, athletes.length, STARTER_ROSTER_SIZE);

      athletes.push(
        rollAthlete(rng, {
          displayName: name,
          primarySport: 'basketball',
          rarity,
          source: 'starter',
          heightCm,
          createdAt: baseCreatedAt,
        }),
      );
    }
  }

  // Soccer: 2 teams × 11 players = 22 athletes
  for (let team = 0; team < 2; team++) {
    for (let positionIndex = 0; positionIndex < 11; positionIndex++) {
      const archetype = SOCCER_ARCHETYPES[positionIndex]!;
      const name = generateUniqueName(rng, usedNames);
      const heightCm = rollHeight(rng, archetype);
      const rarity = rollRarity(rng, athletes.length, STARTER_ROSTER_SIZE);

      athletes.push(
        rollAthlete(rng, {
          displayName: name,
          primarySport: 'soccer',
          rarity,
          source: 'starter',
          heightCm,
          createdAt: baseCreatedAt,
        }),
      );
    }
  }

  // Spares: 6 additional athletes split between basketball and soccer
  for (let i = 0; i < 6; i++) {
    const sport: SportId = i < 3 ? 'basketball' : 'soccer';
    const name = generateUniqueName(rng, usedNames);
    const archetype =
      sport === 'basketball' ? BASKETBALL_ARCHETYPES[i % 5]! : SOCCER_ARCHETYPES[i % 11]!;
    const heightCm = rollHeight(rng, archetype);
    const rarity = rollRarity(rng, athletes.length, STARTER_ROSTER_SIZE);

    athletes.push(
      rollAthlete(rng, {
        displayName: name,
        primarySport: sport,
        rarity,
        source: 'starter',
        heightCm,
        createdAt: baseCreatedAt,
      }),
    );
  }

  return athletes;
}
