/**
 * @spec    001-initial-dev
 * @phase   0 — Foundation, PWA shell, update & offline lifecycle
 * @task    T-0.17 — Spec-header lint rule + traceability report generator
 * @story   —
 * @design  CLAUDE.md §6 (traceability report), 07-decisions.md D-22
 * @invariant INV-15
 *
 * Purpose: generates `docs/traceability.md` — task → files and file → task, both ways — so any
 * piece of code can be traced to the task that asked for it and any task to the code that
 * delivers it. Regenerated at every phase gate and committed.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadKnownIds, traceDirectory, validateHeader, type TracedFile } from './spec-index.ts';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = fileURLToPath(new URL('../src', import.meta.url));
const SPEC_DIR = fileURLToPath(new URL('../specs/001-initial-dev', import.meta.url));
const OUT = fileURLToPath(new URL('../docs/traceability.md', import.meta.url));

export interface TraceReport {
  readonly markdown: string;
  readonly problems: readonly string[];
  readonly fileCount: number;
  readonly taskCount: number;
}

export function buildReport(
  files: readonly TracedFile[],
  known: Awaited<ReturnType<typeof loadKnownIds>>,
): TraceReport {
  const problems: string[] = [];
  const byTask = new Map<string, string[]>();

  for (const file of files) {
    for (const problem of validateHeader(file.header, known)) {
      problems.push(`${file.path}: ${problem.field} — ${problem.message}`);
    }
    for (const task of file.header?.tasks ?? []) {
      const existing = byTask.get(task) ?? [];
      existing.push(file.path);
      byTask.set(task, existing);
    }
  }

  const taskOrder = [...byTask.keys()].sort(compareTaskIds);

  const lines: string[] = [
    '# Traceability',
    '',
    '<!-- Generated by `pnpm trace`. Do not edit by hand. -->',
    '',
    `${files.length} modules under \`src/\`, covering ${taskOrder.length} tasks.`,
    '',
    '## Task → files',
    '',
    '| Task | Files |',
    '|---|---|',
  ];

  for (const task of taskOrder) {
    const paths = (byTask.get(task) ?? []).sort();
    lines.push(`| \`${task}\` | ${paths.map((path) => `\`${path}\``).join(' · ')} |`);
  }

  lines.push(
    '',
    '## File → task',
    '',
    '| File | Tasks | Stories | Invariants |',
    '|---|---|---|---|',
  );

  for (const file of files) {
    const header = file.header;
    lines.push(
      `| \`${file.path}\` | ${fmt(header?.tasks)} | ${fmt(header?.stories)} | ${fmt(header?.invariants)} |`,
    );
  }

  lines.push('');
  return {
    markdown: lines.join('\n'),
    problems,
    fileCount: files.length,
    taskCount: taskOrder.length,
  };
}

function fmt(ids: readonly string[] | undefined): string {
  if (ids === undefined || ids.length === 0) return '—';
  return ids.map((id) => `\`${id}\``).join(' ');
}

/** Sorts `T-0.2` before `T-0.10`, which a plain string sort would not. */
export function compareTaskIds(a: string, b: string): number {
  const parse = (id: string): [number, number] => {
    const match = /T-(\d+)\.(\d+)/.exec(id);
    return [Number(match?.[1] ?? 0), Number(match?.[2] ?? 0)];
  };
  const [aPhase, aTask] = parse(a);
  const [bPhase, bTask] = parse(b);
  return aPhase === bPhase ? aTask - bTask : aPhase - bPhase;
}

async function main(): Promise<void> {
  const files = await traceDirectory(SRC);
  const known = await loadKnownIds(SPEC_DIR);
  const report = buildReport(files, known);

  await mkdir(fileURLToPath(new URL('../docs', import.meta.url)), { recursive: true });
  await writeFile(OUT, report.markdown);

  console.log(`traceability: ${report.fileCount} modules, ${report.taskCount} tasks`);
  console.log(`  → ${OUT.slice(ROOT.length)}`);

  if (report.problems.length > 0) {
    console.error(`\n${report.problems.length} spec-header problem(s):`);
    for (const problem of report.problems) console.error(`  ${problem}`);
    process.exitCode = 1;
  }
}

if (
  process.argv[1] !== undefined &&
  import.meta.url.endsWith(process.argv[1].split('/').pop() ?? '')
) {
  await main();
}
